language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23

android:
  components:
    - build-tools-23.0.1

script:
	- ./gradlew :treasure:build
	- ./gradlew :treasure-compiler:build
