language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-21

android:
  components:
    - build-tools-21.1.1

script:
  - ./gradlew :treasure:build
  - ./gradlew :treasure-compiler:build
